version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 3020:8080
    volumes:
      - ./spec.yml:/usr/share/nginx/html/spec.yaml
    environment:
      API_URL: ./spec.yaml
    depends_on:
      - swagpack
  swagpack:
    build:
      context: .
      dockerfile: ./docker/swagpack/Dockerfile
    volumes:
      - ./src:/app/src
      - ./spec.yml:/app/spec.yml
    working_dir: /app
